# Generated by Django 6.0.5 on 2026-05-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artifacts',
            new_name='Artifact',
        ),
    ]
